/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './clients/admin-api';
export * from './clients/conversation-api';
export * from './clients/image-api';
export * from './clients/shop-api';
export * from './clients/shop-auth-api';
export * from './clients/shop-user-api';

