import { use } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider, useMessages } from 'next-intl';

import useTextDirection from '@/hooks/use-text-direction';
import ProviderComponent from '@/layouts/provider-component';

import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s | SHOPPY',
    default: 'SHOPPY',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { locale: string } }) {
  const locale = params.locale;

  const messages = useMessages();
  const direction = useTextDirection(locale);

  return (
    <html lang={locale} dir={direction}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ProviderComponent>{children}</ProviderComponent>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
