/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressRes
 */
export interface AddressRes {
    /**
     * Address id
     * @type {number}
     * @memberof AddressRes
     */
    'id': number;
    /**
     * First name
     * @type {string}
     * @memberof AddressRes
     */
    'firstName': string;
    /**
     * Last name
     * @type {string}
     * @memberof AddressRes
     */
    'lastName': string;
    /**
     * Phone number
     * @type {string}
     * @memberof AddressRes
     */
    'phone': string;
    /**
     * Address
     * @type {string}
     * @memberof AddressRes
     */
    'address': string;
    /**
     * Country
     * @type {string}
     * @memberof AddressRes
     */
    'country': string;
    /**
     * State
     * @type {string}
     * @memberof AddressRes
     */
    'state': string;
    /**
     * City
     * @type {string}
     * @memberof AddressRes
     */
    'city': string;
    /**
     * Zip code
     * @type {string}
     * @memberof AddressRes
     */
    'zip': string;
}

