/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BadRes
 */
export interface BadRes {
    /**
     * 
     * @type {number}
     * @memberof BadRes
     */
    'statusCode': number;
    /**
     * 
     * @type {string}
     * @memberof BadRes
     */
    'message': string;
}

