/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteImagesDto
 */
export interface DeleteImagesDto {
    /**
     * keys of images
     * @type {Array<string>}
     * @memberof DeleteImagesDto
     */
    'keys': Array<string>;
}

