/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessageDto
 */
export interface MessageDto {
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    'content': string;
    /**
     * 
     * @type {number}
     * @memberof MessageDto
     */
    'conversationId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    'userUID'?: string;
}

