/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * Id
     * @type {number}
     * @memberof Message
     */
    'id': number;
    /**
     * Created at
     * @type {string}
     * @memberof Message
     */
    'createdAt': string;
    /**
     * Message content
     * @type {string}
     * @memberof Message
     */
    'content': string;
    /**
     * User id
     * @type {string}
     * @memberof Message
     */
    'userId': string;
    /**
     * Conversation id
     * @type {number}
     * @memberof Message
     */
    'conversationId': number;
}

