/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProductDto } from './product-dto';

/**
 * 
 * @export
 * @interface ProductsRes
 */
export interface ProductsRes {
    /**
     * 
     * @type {Array<ProductDto>}
     * @memberof ProductsRes
     */
    'products': Array<ProductDto>;
    /**
     * 
     * @type {number}
     * @memberof ProductsRes
     */
    'total': number;
}

