/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const QueryOrder = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;

export type QueryOrder = typeof QueryOrder[keyof typeof QueryOrder];



