/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * First name of a user
     * @type {string}
     * @memberof RegisterDto
     */
    'firstName'?: string;
    /**
     * Surname of a user
     * @type {string}
     * @memberof RegisterDto
     */
    'lastName'?: string;
    /**
     * Email of a user
     * @type {string}
     * @memberof RegisterDto
     */
    'email': string;
    /**
     * Password of a user
     * @type {string}
     * @memberof RegisterDto
     */
    'password': string;
}

