/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ShopUserRes } from './shop-user-res';

/**
 * 
 * @export
 * @interface ShopLoginRes
 */
export interface ShopLoginRes {
    /**
     * 
     * @type {ShopUserRes}
     * @memberof ShopLoginRes
     */
    'user': ShopUserRes;
    /**
     * 
     * @type {string}
     * @memberof ShopLoginRes
     */
    'status': string;
}

