/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserRes
 */
export interface UserRes {
    /**
     * 
     * @type {number}
     * @memberof UserRes
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'displayName': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'signInProvider': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'uid': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'avatar': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'avatarUrl': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof UserRes
     */
    'accountType': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserRes
     */
    'isBlocked': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserRes
     */
    'emailVerified': boolean;
}

