/* tslint:disable */
/* eslint-disable */
/**
 * shoppy
 * An API to do awesome things
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * Id
     * @type {number}
     * @memberof User
     */
    'id': number;
    /**
     * Created at
     * @type {string}
     * @memberof User
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastName'?: string;
    /**
     * Display name
     * @type {string}
     * @memberof User
     */
    'displayName': string;
    /**
     * User ID
     * @type {string}
     * @memberof User
     */
    'uid': string;
    /**
     * Avatar URL
     * @type {string}
     * @memberof User
     */
    'avatar': string;
    /**
     * Avatar URL
     * @type {string}
     * @memberof User
     */
    'avatarUrl': string;
}

